### ISSUE TITLE
It keeps crashing into bigger blobs

### ISSUE THREAD

**Issue by g3m1n1** [leomwu/agario-bot#15]
I've set intuition at 400 to avoid bigger blobs but it crashes into them anyway

**Comment by phadeb** [comment]
it detects the center of the blobs instead of edges.

**Comment by g3m1n1** [comment]
But, how do I stop it from following bigger blobs till it gets eaten?

**Comment by eaglgenes101** [comment]
Same concern.

**Comment by LeoWuVinci** [comment]
Fixed with imminent danger behavior
