### ISSUE TITLE
Bookmarklet?

### ISSUE THREAD

**Issue by jonahsnider** [leomwu/agario-bot#17]
This is all JavaScript based, so in theory, it could be run in a bookmarklet.

**Comment by LeoWuVinci** [comment]
I'll have to come back to this but I believe the browser will not let me make a websocket connection to make this happen.

**Comment by minecrafter1094** [comment]
@leomwu Also, if successfully there was a way to run Javascript that runs a JS file, what file would that be? I looked at the manifest and from what I found, it runs a couple files, is one at the top of the files, that would run the others when finished?
