### ISSUE TITLE
Potential extra tick every tick

### ISSUE THREAD

**Issue by Pheelbert** [leomwu/agario-bot#24]
Not so sure if it's done on purpose, I can't say I fully understand how the ticking works since there's no setTimeout.. Probably has to do with the game code, but hey, if you remove the line it still works :P.

![image](https://cloud.githubusercontent.com/assets/5648665/8027640/747e21b6-0d69-11e5-9f3e-b06ddc4fd0d4.png)

**Comment by LeoWuVinci** [comment]
Anything that starts with "on" is something outside of the object to hook in as an event.
