### ISSUE TITLE
Select best route to avoid more than one enemy at once

### ISSUE THREAD

**Issue by N0zz** [leomwu/agario-bot#26]
I would say the best option would be to mesure angles between "enemies" and choose biggest one to use as escape route. Example: http://i.imgur.com/LwclU4a.png
For now AI will choose one of from the purple routes and will change it really fast, due to change of the distance between "me" and each enemy. It result in staying almost in one place, just waiting to be "eaten" by one of them... But it is really simple, that it should choose white route. Everyone would act like that...
Also similar thing if its edge of the map or something. It stays and waits for one from 2-3 enemies...
- It could split/shot if even biggest angle is to small and enemies speed is to big.
- Sometimes biggest angle is not the best answear. When one or two of the enemies are really big and slow, it will be possible to pass close to them and it would have higher success chance than chosing biggest angle(needs test and calculations to select best possible numbers for enemy speed, my speed, angles etc).
- It seems to work like that, but only if enemies are far away and distances between enemies and me doesn't change(I mean enemy 1 distance is higher than enemy 2 distance for example and it stays higher). If it changes, AI act like it doesn't know what to do.
- I don't know if I did manage to explain what I meant. But you have to forgive me. English isn't my native language ;P

**Comment by JProgrammerJules** [comment]
Yeah, your idea is good. Leo could improve that ^^

**Comment by LeoWuVinci** [comment]
It already does this but instead of using angles, it takes the average of all the enemies and avoids that imaginary enemy.  The result is the same direction without having to compute angles.  The only reason it may not do what you expect is because "Avoid nearest larger blob" may be set too low.
