### ISSUE TITLE
Suggestion: Support reciprocal altruism

### ISSUE THREAD

**Issue by eaglgenes101** [leomwu/agario-bot#27]
I just watch my cell shoot a mass, then watched as a recipient cell took it and shot back a mass, before my cell immediately went in and tried to splitkill that cell. Needless to say, this was a bit disheartening. 

I suggest, in the chat movements category, to incorporate reciprocal altruism: The AI tries not to harm cells it's traded shot masses with. This might open up new strategies, or it might just bomb. But we can't know until it's incorporated.

**Comment by LeoWuVinci** [comment]
haha what a troll bot.  Sorry but I decided not to implement team-related features to keep the project to a manageable size.  It shoots mass only to bait.
