### ISSUE TITLE
Instructions for build?

### ISSUE THREAD

**Issue by vmrob** [leomwu/agario-bot#29]
This is the kind of project that I think would be really fun to contribute to, but I'm a little unsure how to start development. Specifically, I'm not sure if any build tools are required to compile larger main_out*.js files.

Are there any build instructions?

**Comment by LeoWuVinci** [comment]
There is no need to build anything for this project.  First follow the youtube video on the README to understand how to load it.  After that you can modify it directly.  As for contributing to the code, it's best to just fork it atm.
