### ISSUE TITLE
Request Feature:  AI Rotational Movement

### ISSUE THREAD

**Issue by johnnybainguyen** [leomwu/agario-bot#31]
Osmos Game inspired idea.

Have the AI movement rotate on an axis to give the AI better mobility based on weight decisions.  So it factors in all weighted possibilities in an area and move in a circular motion to get the most food.  So it sweeps an area to get the most bang.  

This will also give the AI an advantage over other players making it harder to be eaten.  Point-to-point movement don't play well against circle of death. 

Rotation around a virus gives some massive protection against impending doom. 

Noticed when AI gets stuck between two big blobs, the AI gets afraid and doesn't move.  Cat trapped in a corner!

**Comment by LeoWuVinci** [comment]
Because there's very little inertia in the game engine.  I don't find a rotational based movement is really necessary.  Plus AposBot is already heavily-based on this idea and do not wish to duplicate his code.
