### ISSUE TITLE
Request Feature:  Override Command

### ISSUE THREAD

**Issue by johnnybainguyen** [leomwu/agario-bot#32]
Have the player be able to assist the AI in difficult situations by overriding it's action.  Not sure if this suits the purpose of a purely AI bot.  Maybe the AI bot can learn from the player's command and tell it NO.  BAD KITTY!

**Comment by LeoWuVinci** [comment]
If the AI can be setup to actually learn from player's commands, this would be great.  Otherwise it would not really help the AI learn and can actually make it learn bad things.  It would be a bit too much for this project but a great fork possibility.
