### ISSUE TITLE
Request Feature:  Dynamic Considerations based on Life cycle of a cell

### ISSUE THREAD

**Issue by johnnybainguyen** [leomwu/agario-bot#33]
Have consideration change based on the life cycle of a cell.  

Early game:  More to deal with food

Mid game:  Balance of food and eating other players

End game:  Staying alive and waiting for the perfect time to get bigger

**Comment by LeoWuVinci** [comment]
I do think there is merit in this however I also believe the considerations can be fairly robust in handling the different game states simply by looking at it's current size.  Still I think it's a good fork idea.
