### ISSUE TITLE
Request Feature:  Dynamic Considerations based on situation

### ISSUE THREAD

**Issue by johnnybainguyen** [leomwu/agario-bot#34]
Have consideration change based on situation.  Having the considerations constantly change based on threat level.  Can use similar situations from past games to learn what to do in different situations.  

High threat situations when many big enemies are nearby.  Switch consideration on high alert running away. 

Farm Mode:  No enemies nearly, so eat nom nom nom

Player size:  Learn from player tendencies, like being super small means getting ignored by massive blobs.  
-Similar size blobs tend to chase and are much less of a threat and can be kited.  
-Blobs 3 times bigger plus serve as a higher threat because they can eject kill
-Blobs too massive will probably not bother with the small bot
-Might seem counter-intuitive, but blobs that bigger are not bigger threat

Some other stuff.  Apologies if I'm overlooking anything because I haven't looked at the code.

**Comment by LeoWuVinci** [comment]
The considerations should be implemented with these in mind.  I might make it be able to learn how to modify it's considerations more than once per game session but it's definitely an advance feature that could be very hard to debug.
