### ISSUE TITLE
How game data is grabbed

### ISSUE THREAD

**Issue by matthewr6** [leomwu/agario-bot#38]
A few other bots seem to grab data in the same way, but even a little documentation on the functions/variables used to get the game's data would be amazing.

**Comment by Gjum** [comment]
The functions and variables change frequently (with every new version, every couple days).
A comparison of old/new versions is done at http://ac.gcommer.com/.
The community collects some information about how the client/server communication works in [a wiki](http://agar.gcommer.com).
