### ISSUE TITLE
Frozen after some seconds

### ISSUE THREAD

**Issue by Acanguven** [leomwu/agario-bot#56]
Everything starts well but after some seconds, it gets frozen. Any idea why this happening and how to solve this?
![screen](https://i.gyazo.com/257731d76ce0df4fcd4ed8e360ed660e.png)
![logs](https://i.gyazo.com/be15177d6e4e7e3dfd190e39bad18689.png)

**Comment by dfgsdfsdf** [comment]
This happens for me as well. PLEASE ADDRESS.
