### ISSUE TITLE
Your Twitch got shut down?! Why?

### ISSUE THREAD

**Issue by PleasePayNoAttentionToMe** [leomwu/agario-bot#6]
What are you going to do now...?

**Comment by alexisetoceane** [comment]
Ban Twitch ? :'(

Twitch : The community has closed this channel due to terms of service violations

**Comment by alexisetoceane** [comment]
Twitch : The community has closed this channel due to terms of service violations

**Comment by LeoWuVinci** [comment]
Agar.io broke the bot i'm currently fixing that.
Afterwards I'm going to send an appeal to twitch make them understand they were in the wrong.
In the meantime I'm streaming at hitbox.tv/GamerLio
