### ISSUE TITLE
Stuck between two blobs

### ISSUE THREAD

**Issue by phadeb** [leomwu/agario-bot#9]
Problem : Acceleration isn't taken into account (only distance) which may cause the bot to get stuck inbetween 2 blobs.

Solution : Implement acceleration and make decisions not with distance but with projected time to reach blobs.

**Comment by LeoWuVinci** [comment]
It does take into account of acceleration.  px and py is the predicted coordinates after velocity and acceleration has been added.

**Comment by phadeb** [comment]
But what makes it stuck between 2 blobs sometimes, going back and forth ?

Also why doesn't use acceleration momentum to calculate the best blobs in it's way instead of say a blob that is a shorter distance but at a 90° angle of the first blob, which creates a deceleration and makes getting that closest blob actually longer ?

**Comment by LeoWuVinci** [comment]
So I decided to take out acceleration and add latency cushion because there really isn't much acceleration happening.  As for getting stuck between 2 blobs, it now escapes based on the enemies movement path which will naturally cause it to more likely move at a 90 degree angle.
